### ISSUE TITLE
Older data?

### ISSUE THREAD

**Issue by ghost** [tuxmann/AzCovidCasesbyZip#1]
Not really an issue...

I do the tool at MickeyLane/ByZip. It would be nice to add your work to it.

Do you have data for earlier days?

Suggest publishing .csv files instead of .xls. Much easier to process by some sort of script + doesn't require Microsoft Word suite

**Comment by tuxmann** [comment]
Feel free to take my work, it's GPL3. I don't have data for earlier days, I should have wrote my script months ago. I'm just running the script on a local PC at the moment. I plan on updating the script to push new files to github or make a google spreadsheet. So far, I don't know how to go back & get older data from their website. If you figure it out, that would be cool. 

I can convert them to CSV instead. Libre Office will open the .xls too

In the future, I want to group all the zip codes by county & city. I want to have a graphic of AZ showing areas where the cases are growing. I want to have cases drop off after 2-3 weeks since the virus should have run its course by then. 

If you have any suggestions, or want to help, I'm all ears. Thanks for checking out the repo.

**Comment by ghost** [comment]
What website are you referring to for your data source?

**Comment by tuxmann** [comment]
https://adhsgis.maps.arcgis.com/apps/opsdashboard/index.html#/84b7f701060641ca8bd9ea0717790906 and there's a "download data" link on the left.
